// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appSettings,
    vehicles,
    trips,
    tripChunks,
    tripEvents,
    driverBaselines,
    tripScores,
    syncQueue,
    tripAccountLinks,
    vehiclesOwnerNamespace,
    tripsVehicleStart,
    tripsStartTime,
    tripEventsTripStart,
    tripScoresTripVersion,
    driverBaselinesOwnerVehicle,
    syncQueueIdempotencyKey,
    syncQueueStateNextAttempt,
  ];
  late final Shape0 appSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 vehicles = Shape1(
    source: i0.VersionedTable(
      entityName: 'vehicles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 trips = Shape2(
    source: i0.VersionedTable(
      entityName: 'trips',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(end_wall_time_micros IS NULL OR end_wall_time_micros >= start_wall_time_micros)',
        'CHECK(end_elapsed_nanos IS NULL OR end_elapsed_nanos >= start_elapsed_nanos)',
        'CHECK(duration_millis IS NULL OR duration_millis >= 0)',
        'CHECK(distance_meters IS NULL OR distance_meters >= 0)',
        'CHECK(telemetry_schema_version > 0)',
        'CHECK(telemetry_confidence IS NULL OR(telemetry_confidence >= 0 AND telemetry_confidence <= 1))',
      ],
      columns: [
        _column_3,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_12,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 tripChunks = Shape3(
    source: i0.VersionedTable(
      entityName: 'trip_chunks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(trip_id, sequence)',
        'CHECK(sequence >= 0)',
        'CHECK(encoding_version > 0)',
        'CHECK(end_elapsed_nanos >= start_elapsed_nanos)',
        'CHECK(byte_length >= 0)',
      ],
      columns: [
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_16,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 tripEvents = Shape4(
    source: i0.VersionedTable(
      entityName: 'trip_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(peak_elapsed_nanos >= start_elapsed_nanos)',
        'CHECK(end_elapsed_nanos >= peak_elapsed_nanos)',
        'CHECK(severity >= 0 AND severity <= 1)',
        'CHECK(confidence >= 0 AND confidence <= 1)',
      ],
      columns: [
        _column_3,
        _column_30,
        _column_42,
        _column_16,
        _column_43,
        _column_34,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 driverBaselines = Shape5(
    source: i0.VersionedTable(
      entityName: 'driver_baselines',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(baseline_schema_version > 0)',
        'CHECK(valid_trip_count >= 0)',
        'CHECK(confidence IS NULL OR(confidence >= 0 AND confidence <= 1))',
        'CHECK(window_start_wall_time_micros IS NULL OR window_end_wall_time_micros IS NULL OR window_end_wall_time_micros >= window_start_wall_time_micros)',
      ],
      columns: [
        _column_3,
        _column_4,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_12,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tripScores = Shape6(
    source: i0.VersionedTable(
      entityName: 'trip_scores',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(score_schema_version > 0)',
        'CHECK(overall_score IS NULL OR(overall_score >= 0 AND overall_score <= 100))',
        'CHECK(confidence IS NULL OR(confidence >= 0 AND confidence <= 1))',
      ],
      columns: [
        _column_3,
        _column_30,
        _column_62,
        _column_57,
        _column_63,
        _column_64,
        _column_61,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 syncQueue = Shape7(
    source: i0.VersionedTable(
      entityName: 'sync_queue',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(operation_id)',
        'CHECK(entity_version >= 0)',
        'CHECK(attempt_count >= 0)',
      ],
      columns: [
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_12,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 tripAccountLinks = Shape8(
    source: i0.VersionedTable(
      entityName: 'trip_account_links',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(trip_id)', 'CHECK(summary_version = 1)'],
      columns: [_column_30, _column_80, _column_81, _column_82],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index vehiclesOwnerNamespace = i1.Index(
    'vehicles_owner_namespace',
    'CREATE INDEX vehicles_owner_namespace ON vehicles (owner_namespace)',
  );
  final i1.Index tripsVehicleStart = i1.Index(
    'trips_vehicle_start',
    'CREATE INDEX trips_vehicle_start ON trips (vehicle_id, start_wall_time_micros)',
  );
  final i1.Index tripsStartTime = i1.Index(
    'trips_start_time',
    'CREATE INDEX trips_start_time ON trips (start_wall_time_micros)',
  );
  final i1.Index tripEventsTripStart = i1.Index(
    'trip_events_trip_start',
    'CREATE INDEX trip_events_trip_start ON trip_events (trip_id, start_elapsed_nanos)',
  );
  final i1.Index tripScoresTripVersion = i1.Index(
    'trip_scores_trip_version',
    'CREATE UNIQUE INDEX trip_scores_trip_version ON trip_scores (trip_id, score_schema_version, scoring_version)',
  );
  final i1.Index driverBaselinesOwnerVehicle = i1.Index(
    'driver_baselines_owner_vehicle',
    'CREATE INDEX driver_baselines_owner_vehicle ON driver_baselines (owner_namespace, vehicle_id)',
  );
  final i1.Index syncQueueIdempotencyKey = i1.Index(
    'sync_queue_idempotency_key',
    'CREATE UNIQUE INDEX sync_queue_idempotency_key ON sync_queue (idempotency_key)',
  );
  final i1.Index syncQueueStateNextAttempt = i1.Index(
    'sync_queue_state_next_attempt',
    'CREATE INDEX sync_queue_state_next_attempt ON sync_queue (state, next_attempt_at_micros)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAtMicros =>
      columnsByName['updated_at_micros']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at_micros',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ownerNamespace =>
      columnsByName['owner_namespace']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get vehicleType =>
      columnsByName['vehicle_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manufacturer =>
      columnsByName['manufacturer']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get modelYear =>
      columnsByName['model_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get calibrationMetadataJson =>
      columnsByName['calibration_metadata_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baselineMetadataJson =>
      columnsByName['baseline_metadata_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtMicros =>
      columnsByName['created_at_micros']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtMicros =>
      columnsByName['updated_at_micros']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'owner_namespace',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'vehicle_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'manufacturer',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'model',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'model_year',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'calibration_metadata_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'baseline_metadata_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at_micros',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startWallTimeMicros =>
      columnsByName['start_wall_time_micros']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endWallTimeMicros =>
      columnsByName['end_wall_time_micros']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startElapsedNanos =>
      columnsByName['start_elapsed_nanos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endElapsedNanos =>
      columnsByName['end_elapsed_nanos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMillis =>
      columnsByName['duration_millis']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get distanceMeters =>
      columnsByName['distance_meters']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get completionState =>
      columnsByName['completion_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get recoveryState =>
      columnsByName['recovery_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get telemetrySchemaVersion =>
      columnsByName['telemetry_schema_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get scoringVersion =>
      columnsByName['scoring_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get eventEngineVersion =>
      columnsByName['event_engine_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mlModelRefsJson =>
      columnsByName['ml_model_refs_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get integrityStatus =>
      columnsByName['integrity_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get telemetryConfidence =>
      columnsByName['telemetry_confidence']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get telemetryQualitySummaryJson =>
      columnsByName['telemetry_quality_summary_json']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cloudSyncState =>
      columnsByName['cloud_sync_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtMicros =>
      columnsByName['created_at_micros']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtMicros =>
      columnsByName['updated_at_micros']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'vehicle_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES vehicles(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_wall_time_micros',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_wall_time_micros',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_elapsed_nanos',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_elapsed_nanos',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_millis',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_19(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'distance_meters',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'completion_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'recovery_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'telemetry_schema_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scoring_version',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'event_engine_version',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ml_model_refs_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'integrity_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_27(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'telemetry_confidence',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'telemetry_quality_summary_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cloud_sync_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get tripId =>
      columnsByName['trip_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sequence =>
      columnsByName['sequence']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get storageReference =>
      columnsByName['storage_reference']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get encodingVersion =>
      columnsByName['encoding_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startElapsedNanos =>
      columnsByName['start_elapsed_nanos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endElapsedNanos =>
      columnsByName['end_elapsed_nanos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get channelSampleCountsJson =>
      columnsByName['channel_sample_counts_json']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get compression =>
      columnsByName['compression']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get atomicWriteStrategy =>
      columnsByName['atomic_write_strategy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get checksumAlgorithm =>
      columnsByName['checksum_algorithm']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get checksum =>
      columnsByName['checksum']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get byteLength =>
      columnsByName['byte_length']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get writeState =>
      columnsByName['write_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtMicros =>
      columnsByName['created_at_micros']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trip_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES trips(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sequence',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'storage_reference',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'encoding_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_elapsed_nanos',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'channel_sample_counts_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'compression',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'atomic_write_strategy',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'checksum_algorithm',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'checksum',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'byte_length',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'write_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tripId =>
      columnsByName['trip_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get eventType =>
      columnsByName['event_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startElapsedNanos =>
      columnsByName['start_elapsed_nanos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get peakElapsedNanos =>
      columnsByName['peak_elapsed_nanos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endElapsedNanos =>
      columnsByName['end_elapsed_nanos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get severity =>
      columnsByName['severity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get severityCalibrationVersion =>
      columnsByName['severity_calibration_version']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get confidence =>
      columnsByName['confidence']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get qualityFlagsJson =>
      columnsByName['quality_flags_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get primaryMeasurementsJson =>
      columnsByName['primary_measurements_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ruleEvidenceJson =>
      columnsByName['rule_evidence_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mlEvidenceJson =>
      columnsByName['ml_evidence_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contextTagsJson =>
      columnsByName['context_tags_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get algorithmVersion =>
      columnsByName['algorithm_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtMicros =>
      columnsByName['created_at_micros']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'event_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'peak_elapsed_nanos',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_44(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'severity',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'severity_calibration_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_46(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'confidence',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'quality_flags_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'primary_measurements_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rule_evidence_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ml_evidence_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'context_tags_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'algorithm_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ownerNamespace =>
      columnsByName['owner_namespace']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lifecycleState =>
      columnsByName['lifecycle_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dimensionStatisticsJson =>
      columnsByName['dimension_statistics_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get baselineSchemaVersion =>
      columnsByName['baseline_schema_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get scoringVersion =>
      columnsByName['scoring_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get validTripCount =>
      columnsByName['valid_trip_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get windowStartWallTimeMicros =>
      columnsByName['window_start_wall_time_micros']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get windowEndWallTimeMicros =>
      columnsByName['window_end_wall_time_micros']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get confidence =>
      columnsByName['confidence']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get createdAtMicros =>
      columnsByName['created_at_micros']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtMicros =>
      columnsByName['updated_at_micros']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'vehicle_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES vehicles(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'lifecycle_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dimension_statistics_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'baseline_schema_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scoring_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'valid_trip_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'window_start_wall_time_micros',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'window_end_wall_time_micros',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_61(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'confidence',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tripId =>
      columnsByName['trip_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get scoreSchemaVersion =>
      columnsByName['score_schema_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get scoringVersion =>
      columnsByName['scoring_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dimensionValuesJson =>
      columnsByName['dimension_values_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get overallScore =>
      columnsByName['overall_score']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get confidence =>
      columnsByName['confidence']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get eligibilityState =>
      columnsByName['eligibility_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get auditContributionsJson =>
      columnsByName['audit_contributions_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baselineId =>
      columnsByName['baseline_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get modelVersionsJson =>
      columnsByName['model_versions_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtMicros =>
      columnsByName['created_at_micros']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'score_schema_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dimension_values_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_64(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'overall_score',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'eligibility_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'audit_contributions_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'baseline_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NULL REFERENCES driver_baselines(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'model_versions_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get operationId =>
      columnsByName['operation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get idempotencyKey =>
      columnsByName['idempotency_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityType =>
      columnsByName['entity_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get entityVersion =>
      columnsByName['entity_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get operationType =>
      columnsByName['operation_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payloadJson =>
      columnsByName['payload_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attemptCount =>
      columnsByName['attempt_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nextAttemptAtMicros =>
      columnsByName['next_attempt_at_micros']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastErrorCode =>
      columnsByName['last_error_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtMicros =>
      columnsByName['created_at_micros']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtMicros =>
      columnsByName['updated_at_micros']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'operation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'idempotency_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'entity_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'operation_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_77(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempt_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'next_attempt_at_micros',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_79(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get tripId =>
      columnsByName['trip_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get consentedAtMicros =>
      columnsByName['consented_at_micros']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get summaryVersion =>
      columnsByName['summary_version']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_81(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'consented_at_micros',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_82(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'summary_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    appSettings,
    vehicles,
    trips,
    tripChunks,
    tripEvents,
    driverBaselines,
    tripScores,
    syncQueue,
    tripAccountLinks,
    accountMetadataCache,
    vehiclesOwnerNamespace,
    tripsVehicleStart,
    tripsStartTime,
    tripEventsTripStart,
    tripScoresTripVersion,
    driverBaselinesOwnerVehicle,
    syncQueueIdempotencyKey,
    syncQueueStateNextAttempt,
  ];
  late final Shape0 appSettings = Shape0(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 vehicles = Shape1(
    source: i0.VersionedTable(
      entityName: 'vehicles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 trips = Shape2(
    source: i0.VersionedTable(
      entityName: 'trips',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(end_wall_time_micros IS NULL OR end_wall_time_micros >= start_wall_time_micros)',
        'CHECK(end_elapsed_nanos IS NULL OR end_elapsed_nanos >= start_elapsed_nanos)',
        'CHECK(duration_millis IS NULL OR duration_millis >= 0)',
        'CHECK(distance_meters IS NULL OR distance_meters >= 0)',
        'CHECK(telemetry_schema_version > 0)',
        'CHECK(telemetry_confidence IS NULL OR(telemetry_confidence >= 0 AND telemetry_confidence <= 1))',
      ],
      columns: [
        _column_3,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_12,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 tripChunks = Shape3(
    source: i0.VersionedTable(
      entityName: 'trip_chunks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(trip_id, sequence)',
        'CHECK(sequence >= 0)',
        'CHECK(encoding_version > 0)',
        'CHECK(end_elapsed_nanos >= start_elapsed_nanos)',
        'CHECK(byte_length >= 0)',
      ],
      columns: [
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_16,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 tripEvents = Shape4(
    source: i0.VersionedTable(
      entityName: 'trip_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(peak_elapsed_nanos >= start_elapsed_nanos)',
        'CHECK(end_elapsed_nanos >= peak_elapsed_nanos)',
        'CHECK(severity >= 0 AND severity <= 1)',
        'CHECK(confidence >= 0 AND confidence <= 1)',
      ],
      columns: [
        _column_3,
        _column_30,
        _column_42,
        _column_16,
        _column_43,
        _column_34,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 driverBaselines = Shape5(
    source: i0.VersionedTable(
      entityName: 'driver_baselines',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(baseline_schema_version > 0)',
        'CHECK(valid_trip_count >= 0)',
        'CHECK(confidence IS NULL OR(confidence >= 0 AND confidence <= 1))',
        'CHECK(window_start_wall_time_micros IS NULL OR window_end_wall_time_micros IS NULL OR window_end_wall_time_micros >= window_start_wall_time_micros)',
      ],
      columns: [
        _column_3,
        _column_4,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_12,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tripScores = Shape6(
    source: i0.VersionedTable(
      entityName: 'trip_scores',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(score_schema_version > 0)',
        'CHECK(overall_score IS NULL OR(overall_score >= 0 AND overall_score <= 100))',
        'CHECK(confidence IS NULL OR(confidence >= 0 AND confidence <= 1))',
      ],
      columns: [
        _column_3,
        _column_30,
        _column_62,
        _column_57,
        _column_63,
        _column_64,
        _column_61,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 syncQueue = Shape7(
    source: i0.VersionedTable(
      entityName: 'sync_queue',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(operation_id)',
        'CHECK(entity_version >= 0)',
        'CHECK(attempt_count >= 0)',
      ],
      columns: [
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_12,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 tripAccountLinks = Shape8(
    source: i0.VersionedTable(
      entityName: 'trip_account_links',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(trip_id)', 'CHECK(summary_version = 1)'],
      columns: [_column_30, _column_80, _column_81, _column_82],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 accountMetadataCache = Shape9(
    source: i0.VersionedTable(
      entityName: 'account_metadata_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(user_id, entity_type, entity_id)',
        'CHECK(entity_type IN (\'profile\', \'vehicle\'))',
        'CHECK(revision >= 0)',
      ],
      columns: [
        _column_80,
        _column_71,
        _column_72,
        _column_83,
        _column_84,
        _column_85,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index vehiclesOwnerNamespace = i1.Index(
    'vehicles_owner_namespace',
    'CREATE INDEX vehicles_owner_namespace ON vehicles (owner_namespace)',
  );
  final i1.Index tripsVehicleStart = i1.Index(
    'trips_vehicle_start',
    'CREATE INDEX trips_vehicle_start ON trips (vehicle_id, start_wall_time_micros)',
  );
  final i1.Index tripsStartTime = i1.Index(
    'trips_start_time',
    'CREATE INDEX trips_start_time ON trips (start_wall_time_micros)',
  );
  final i1.Index tripEventsTripStart = i1.Index(
    'trip_events_trip_start',
    'CREATE INDEX trip_events_trip_start ON trip_events (trip_id, start_elapsed_nanos)',
  );
  final i1.Index tripScoresTripVersion = i1.Index(
    'trip_scores_trip_version',
    'CREATE UNIQUE INDEX trip_scores_trip_version ON trip_scores (trip_id, score_schema_version, scoring_version)',
  );
  final i1.Index driverBaselinesOwnerVehicle = i1.Index(
    'driver_baselines_owner_vehicle',
    'CREATE INDEX driver_baselines_owner_vehicle ON driver_baselines (owner_namespace, vehicle_id)',
  );
  final i1.Index syncQueueIdempotencyKey = i1.Index(
    'sync_queue_idempotency_key',
    'CREATE UNIQUE INDEX sync_queue_idempotency_key ON sync_queue (idempotency_key)',
  );
  final i1.Index syncQueueStateNextAttempt = i1.Index(
    'sync_queue_state_next_attempt',
    'CREATE INDEX sync_queue_state_next_attempt ON sync_queue (state, next_attempt_at_micros)',
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityType =>
      columnsByName['entity_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payloadJson =>
      columnsByName['payload_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get revision =>
      columnsByName['revision']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sourceLocalVehicleId =>
      columnsByName['source_local_vehicle_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_84(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_85(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_local_vehicle_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
